# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jalombar <jalombar@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/04/17 13:48:12 by jalombar          #+#    #+#              #
#    Updated: 2025/02/03 15:04:05 by jalombar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = c++   
FLAGS = -Wall -Werror -Wextra -std=c++98
CLASSES = HumanA.cpp HumanB.cpp Weapon.cpp
SRCS = main.cpp $(CLASSES)
HEADER = Weapon.hpp HumanA.hpp HumanB.hpp
NAME = violence

all: $(NAME)

$(NAME): $(SRCS)
	@$(CC) $(FLAGS) -o $@ $(SRCS)
	
clean:

fclean: clean
	rm -f $(NAME)

re: fclean all
